### ISSUE TITLE
Is "If" an Action or a Directive?

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#14]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issue/11)

Hi Richard (@cpsolver),

On the [Dashrep.Org](https://dashrep.org/) webpage, the following are clearly stated as being directives:

- hyphen-here
- no-space
- one-space
- non-breaking-space
- new-line
- empty-line

However, in the section of "**Decision-related phrases**", when describing `if-yes-begin`, there is the following statement:

![if-action-or-directive](https://github.com/user-attachments/assets/24f78efb-99cf-431f-822d-6b07603f258c)

Here "if" is described both as an action and as a directive. Is there a distinction or is there an overlap between the terms?

It would appear from the Sublime Text syntax highlighting (of the [specifications_phrase_categories_and_names.txt](https://github.com/cpsolver/Dashrep-language/blob/de3cde714c25fff499999fb434f34c18d7b71745/specifications_phrase_categories_and_names.txt#L47-L55) file) that all the following are directives:

![if-directives-sublime-text](https://github.com/user-attachments/assets/7e756207-b03f-4904-b6b0-8ff8ce07b567)

Is that the intention based on the specific-coloured highlighting for each of these phrases?

If that is the case, then **_all_** of the [phrases](https://github.com/cpsolver/Dashrep-language/blob/de3cde714c25fff499999fb434f34c18d7b71745/specifications_phrase_categories_and_names.txt#L2-L15) in the **Hyphens, spaces, lines, & special characters** section (some of which are mentioned above), are also directives. Can you confirm that this is a logical conclusion, based on the coloured highlighting?

![hyphen-spaces-etc-directives](https://github.com/user-attachments/assets/6e71560e-2649-4ba2-a8da-bf36a2e57e60)

Kind Regards,
Liam

**Comment by cpsolver** [comment]
After some initial head scratching I recognize that "if-yes-then" and "if-no-then" are directives, not actions.  Liam, thanks for catching yet another inconsistency.

**Comment by cpsolver** [comment]
I finally was able to merge your/Liam's changes into my local repository.  (Long story....  It was my first merge.)  Liam, thank you for the corrections!  Just now I generated the documentation page.  I see your improvements!  I also see I used the word "action" instead of "directive" for "if-yes-begin" and "if-no-begin" and "if-else" and "if-end".  Since you have started some of these edits would you mind making the other edits in the same four definitions?  As a clarification, the actions that begin "yes-or-no-..." and "yes-if-..." and "no-if-..." are correctly identified as actions (not directives).  Thanks!!

**Comment by cpsolver** [comment]
I just made these changes after downloading all of your changes.  So this issue is fixed as far as I know.  Again, thank you Liam for pointing out the need for this documentation correction.
