### ISSUE TITLE
Comment about bug in function

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#21]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issues/20)

Hi Richard (@cpsolver),

The file [template-function-yes-or-no-same-two-phrase-definitions.txt](https://github.com/cpsolver/Dashrep-language/blob/40f75ff8ce58736f53fd86abcc73130609d80db5/compiler_source/6_actions_perl/template-function-yes-or-no-same-two-phrase-definitions.txt#L1) has the following comment:

`combee **** todo: fix bug in this function, then delete associated inline template to switch to standardized template **** comenn`

The parallel C/C++ **template-function-yes-or-no-same-two-phrase-definitions.txt**  also has the same comment:   https://github.com/cpsolver/Dashrep-language/blob/40f75ff8ce58736f53fd86abcc73130609d80db5/compiler_source_c_language_runtime/action_specific/template-function-yes-or-no-same-two-phrase-definitions.txt#L1 Is this bug a current problem or has it been addressed already, but the comment has not been updated?

Kind Regards,
Liam

**Comment by cpsolver** [comment]
I'm not certain.  I'm not aware of a bug for this action.  I think this file is not currently used.  I think I had planned to fix this file and later use it so that the action "yes-or-no-same-two-phrase-definitions" used a more standardized/generic implementation.  We can leave this as an open future-development issue even though it's not a bug that affects the compiler.  I'm not sure how this kind of issue is usually handled.  The comment is copied into the C/C++ version as a reminder.  FWIW I doubt I'll live long enough to finish writing the C/C++ version.

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issues/21)

Hi Richard (@cpsolver),

Since the commented bug does not affect the compiler, I will close this issue. There is a [default set of labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels), such as `bug`, `enhancement` that can be applied to issues, pull requests and discussions. One could perhaps flag this is issue with the default `enhancement` label, so that it can be tracked for future work. 

A repo can create its own set of labels, complete with a label Name, Description and Color. For example, the PLDB repo has [a distinct set of labels](https://github.com/breck7/pldb/labels). For example, the repo has flagged certain issues with the "[Help Wanted](https://github.com/breck7/pldb/labels/helpWanted)" label.

These labels might give you an idea of an suitable custom label for future work in the Dashrep repo if that is required.

Kind Regards,
Liam
